services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      ENV: production
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jingyuyan
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Mount volume for persistence

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

volumes:
  db_data: # Define the db data volumes      
